KitchenMastery/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('recipes/',include(('recipes.urls','recipes'),namespace='recipes')),
    path('store/',include(('store.urls','store'),namespace='store')),
    path('tips/',include(('tips.urls','tips'),namespace='tips')),
    path('userauth/',include('django.contrib.auth.urls')),
    path('userauth/',include(('userauth.urls','userauth'),namespace='userauth')),
    
    
]+ static (settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name="home"),
]

recipes/urls.py
from django.urls import path
from .views import RecipeDetailView
from .views import RecipeListView

urlpatterns = [
    path('',RecipeListView.as_view(),name='recipes' ),
    path('recipe/<int:pk>/',RecipeDetailView.as_view(), name = "recipe-detail"),
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store_view, name='store'),
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('increase-cart-item/<int:product_id>/', views.increase_cart_item, name='increase-cart-item'),
    path('decrease-cart-item/<int:product_id>/', views.decrease_cart_item, name='decrease-cart-item'),
]

tips/urls.py
from django.urls import path
from .views import AddTipView
from .views import TipsView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'tips'
urlpatterns = [
    path('',TipsView.as_view(),name='tips'),
    path('add_tip/',AddTipView.as_view(), name='add_tip'),
]+ static (settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from .views import UserRegistrationView
from django.contrib.auth.views import LoginView,LogoutView
app_name = 'userauth'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models

class Recipe(models.Model):
    name = models.TextField()
    description = models.TextField()
    image = models.TextField()
    ingredients = models.TextField()  # Field to store ingredients as a comma-separated string
    instructions = models.TextField()  # Field to store instructions as a comma-separated string

    def get_ingredients(self):
        return self.ingredients.split(',') if self.ingredients else []

    def get_instructions(self):
        return self.instructions.split(',') if self.instructions else []
    

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.CharField(max_length=400)


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')
    

    def calculate_total_price(self):
        cart_items = CartItem.objects.filter(cart=self)
        total_price = sum(float(item.product.price.to_decimal()) * item.quantity for item in cart_items)
        return total_price

tips/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import os

class Tip(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
   date = models.DateTimeField(auto_now_add=True)
   subject = models.CharField(max_length=1000)
   description = models.TextField()
   image= models.ImageField(null=True,blank=True, upload_to ="images/")

   def get_absolute_url(self): 
       return reverse('tips')

userauth/models.py
from django.db import models

# Create your models here.

tips/forms.py
from django import forms
from .models import Tip

class TipForm(forms.ModelForm):
    class Meta:
        model = Tip
        fields = ['subject', 'description','image']

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter the description here'}),
        }

home/views.py
from django.shortcuts import render
# Create your views here.
def home( request):
    return render(request, 'home.html',{})

recipes/views.py
from .models import Recipe
from django.views.generic import ListView, DetailView

class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes.html'

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipedetails.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ingredients'] = self.object.get_ingredients()
        context['instructions'] = self.object.get_instructions()
        return context
    

store/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from .models import Product, Cart, CartItem

def store_view(request):
    item_objects = Product.objects.all()
    context = {'item_objects': item_objects}
    return render(request, 'store.html', context)

def cart_view(request):
    try:
        cart_items = CartItem.objects.filter(cart__user=request.user)
        cart = request.user.cart
    except ObjectDoesNotExist:
        cart_items = []
        cart = None

    context = {'cart_items': cart_items, 'cart': cart}
    return render(request, 'cart.html', context)

def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, product=product)

    if not item_created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('store:store')

def increase_cart_item(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart = request.user.cart
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('store:cart')

def decrease_cart_item(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart = request.user.cart
    cart_item = cart.cartitem_set.get(product=product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('store:cart')

tips/views.py
from django.views.generic import ListView, CreateView
from .models import Tip
from .forms import TipForm
from django.urls import reverse_lazy

class TipsView(ListView):
   model = Tip
   template_name = 'tips.html'

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['user'] = self.request.user
       return context

class AddTipView(CreateView):
   model = Tip
   template_name = 'add_tip.html'
   form_class = TipForm
   success_url = reverse_lazy('tips:tips')

   def form_valid(self, form):
      self.object = form.save(commit=False)
      if self.request.user.is_authenticated:
          self.object.user = self.request.user
      else:
        self.object.user = None
      self.object.save()
      return super().form_valid(form)

userauth/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class UserRegistrationView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url =reverse_lazy('login')

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <script src="https://unpkg.com/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Latest compiled JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'images/icon.jpg' %}" type="image/x-icon" />
  <!-- jQuery -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js"></script>

</head>

<body>

  <nav class="nav-style navbar navbar-expand-sm container-fluid sticky-top">
    <a class="navbar-brand" href="{% url 'home:home' %}">
      <img src="{% static 'images/Logo.png' %}" alt="KitechMastery Logo" class="logo-height">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav navigation">
        <li class="nav-item">
          <a class="nav-link  {% if request.path == '/' %} active-page {% endif %}"
            href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if '/store/' in request.path %} active-page {% endif %}"
            href="{% url 'store:store' %}">Our Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if '/recipes/' in request.path %} active-page {% endif %}"
            href="{% url 'recipes:recipes' %}">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if '/tips/' in request.path %} active-page {% endif %}"
            href="{% url 'tips:tips' %}">Cooking Tips</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <div class="d-flex ms-auto navigation">
        <a href="{% url 'store:cart' %}"><span class="bi bi-cart3 cart-style "></span></a>
      </div>
      <button id="logoutBtn" class="btn btn-primary button button-margin">Logout</button>
      {% else %}
      <a href="{% url 'userauth:login' %}" class="btn btn-primary button ms-auto button-margin">Login</a>
      {% endif %}
    </div>
  </nav>
  <!-- Logout Modal -->
  <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirmationModalLabel">Logout</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are You sure you want to log out?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <a href="{% url 'userauth:logout' %}" class="btn btn-primary button">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById('logoutBtn').addEventListener('click', function () {
      var myModal = new bootstrap.Modal(document.getElementById('logoutModal'));
      myModal.show();
    });
  </script>

  {% block content %}
  {% endblock %}

</body>

</html>

home/templates/home.html
{%extends 'base.html'%}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="align-center container-fluid home-intro-margin">
  <div class="row justify-content-center">
    <div class="col-md-12 content-head">
      <h1 class="mb-4 display-2 home-heading">Unleash Your Cooking Creativity</h1>
      <p class="mbr-text mbr-fonts-style mb-4 display-7">
        Spice up your kitchen with our premium cooking supplies and unlock endless culinary possibilities. Discover
        the perfect tools and ingredients to bring your recipes to life.
      </p>
    </div>
  </div>
  <div class="row mt-5 justify-content-center">
    <div class="col-lg-8 col-12 thumbnail text-center">
      <img src="{% static 'images/kitchen.jpg' %}" class="img-fluid">
    </div>
  </div>
</div>
<div class="container home-intro-margin ">
  <div class="row">
    <div class="col-md-12 mb-4">
      <h2 class="text-center display-2 heading ">Our Services</h2>
    </div>
    <div class="col-md-4 ">
      <div class="card mb-4 rounded-2 card-body">
        <img src="{% static 'images/supplies.jpg' %}" class="card-img-top rounded-top-2" alt="Service 1">
        <div class="card-body">
          <h5 class="card-title">Kitchen Supplies</h5>
          <p class="card-text service-text-height">Find high-quality tools, cookware, and accessories for your kitchen.
          </p>
          <a href="{% url 'store:store' %}" class="btn btn-primary button">Shop Now</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4 rounded-2 card-body">
        <img src="{% static 'images/recepies.jpg' %}" class="card-img-top rounded-top-2" alt="Service 2">
        <div class="card-body">
          <h5 class="card-title">Cooking Recipes</h5>
          <p class="card-text service-text-height">Explore a diverse collection of recipes for various cuisines and
            occasions.</p>
          <a href="{% url 'recipes:recipes' %}" class="btn btn-primary button">Discover</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4 rounded-2 card-body">
        <img src="{% static 'images/tips.jpg' %}" class="card-img-top rounded-top-2" alt="Service 3">
        <div class="card-body">
          <h5 class="card-title">Cooking Tips</h5>
          <p class="card-text service-text-height">Get valuable insights and techniques to improve your cooking skills
            and enhance your culinary experience.</p>
          <a href="{% url 'tips:tips' %}" class="btn btn-primary button">Learn More</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

recipes/templates/recipedetails.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{recipe.name}} Recipe{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center mb-4 display-2 heading">{{ recipe.name }}</h1>
                <div>
                    <h3>Ingredients:</h3>
                    <ul class="ingredient-list list-style">
                        {% for ingredient in ingredients %}
                            <li class="ingredient-item"><span class="bullet-point"></span>{{ ingredient }}</li>
                        {% endfor %}
                    </ul>
                    <br><br>
                    <h3>Instructions:</h3>
                    <ol class="instruction-list list-style">
                        {% for instruction in instructions %}
                            <li>{{ instruction }}</li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

recipes/templates/recipes.html
{%extends 'base.html'%}
{% load static %}
{% block title %}Recipes{% endblock %}
{% block content %}
<div class="container mt-5 main-content">
  <h1 class="text-center mb-4 text-center display-2 heading">Recipes</h1>
  <div class="row">
  
    {% for recipe in recipe_list %}
      <div class="col-lg-4 col-md-6 mb-4">
          <div class="card  mb-4 rounded-2 card-body">
              <img src="{% static recipe.image %}"  alt="{{recipe.name}}" class="card-img-top rounded-top-2">
              <div class="card-body">
                <h5 class="card-title recipe-link"><a href="{% url 'recipes:recipe-detail' recipe.pk %}" >{{recipe.name}}</a></h5>
                <p class="card-text service-text-height">{{recipe.description}}</p>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

store/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center mb-4 text-center display-2 heading">Cart Items</h1>
      {% if cart %}
        <table class="table table-responsive">
          {% for item in cart_items %}
        <tr>
          <td>
            <div class="d-flex align-items-center">
              <img src="{% static item.product.image %}" alt="{{item.product.name}}"
                class="fixed-height cart-item-img card-img-top">
              <div class="ms-3">
                <h5 class="mb-1">{{item.product.name}}</h5>
                <p class="mb-1 card-subtitle mb-2 text-muted">BHD {{item.product.price}}</p>
                <div class="d-flex ms-auto align-items-center">
                  <form action="{% url 'store:increase-cart-item' item.product.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary quantity-btn increase-quantity" type="submit">+</button>
                  </form>
                  <span class="item-quantity mx-2">{{ item.quantity }}</span>
                  <form action="{% url 'store:decrease-cart-item' item.product.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary quantity-btn decrease-quantity" type="submit">-</button>
                  </form>
                </div>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </table>
      <div class="mt-3 p-3 bg-light border text-center total-price">
        <h4><span class="total-price-title">Total Price: </span>BHD {{ cart.calculate_total_price|floatformat:2 }}</h4>
      </div>
      <div class="d-flex justify-content-center">
        <button class="btn btn-primary button" id="confirmOrderBtn">Confirm Order</button>
      </div>
      <br>
      {% else %}
        <p class="text-center">No items in the cart.</p>
      {% endif %}
    </div>
  </div>
</div>
<!-- Confirmation Modal -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmationModalLabel">Order Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Your order has been confirmed successfully!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary button" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<script>
  document.getElementById('confirmOrderBtn').addEventListener('click', function () {
    var myModal = new bootstrap.Modal(document.getElementById('confirmationModal'));
    myModal.show();
  });
</script>


{% endblock %}

store/templates/store.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Our Store{% endblock %}
{% block content %}
<div class="container mt-5 main-content">
    <h1 class="text-center mb-4 text-center display-2 heading">Our Store</h1>
    <div class="row">

        {% for item in item_objects %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card mb-4 rounded-2">
                <img src="{% static item.image %}" alt="{{item.name}}">
                <div class="card-body card-body-padding">
                    <div class="description-height">
                        <h5 class="card-title">{{item.name}}</h5>
                        <p class="card-text">{{item.description}}</p>
                    </div>
                    <h6 class="card-subtitle mb-2 text-muted d-flex justify-content-center">BHD {{item.price}}</h6>
                    <div class="d-flex justify-content-center">
                        {% if user.is_authenticated %}
                        <form action="{% url 'store:add-to-cart' item.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-primary add-to-basket button" type="submit" name="cart_items"
                                value="{{ item.id }}">Add to Basket</button>
                        </form>
                        {% else %}
                        <form action="{% url 'userauth:login' %}">
                            {% csrf_token %}
                            <button class="btn btn-primary add-to-basket button" type="submit" name="cart_items"
                                value="{{ item.id }}">Add to Basket</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

tips/templates/add_tip.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Share a Tip{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="text-center mb-4 text-center display-2 heading"> Share a Cooking Tip!</h1>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.subject.label_tag }}
                        {{ form.subject }}
                    </div>
                    <div class="mb-3">
                        {{ form.description.label_tag }}
                        {{ form.description }}
                    </div>
                    <div class="mb-3">
                        {{ form.image.label_tag }}
                        {{ form.image }}
                    </div>
                    <button class="btn btn-primary button" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tips/templates/tips.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cooking Tips{% endblock %}
{% block content %}
<div class="container">
  <h1 class="text-center mb-4 text-center display-2 heading" >Cooking Tips</h1>
  <p class="text-center" style="font-size: large;">Join us in building a collection of helpful cooking tips for aspiring chefs and home cooks.</p>
  <span class="d-flex justify-content-center"><a href="{% url 'tips:add_tip' %}" class="btn btn-primary button">Share a Tip</a></span>
  <br><br>
  <div class="row">
    <div class="col-md-6 col-lg-4 tip-width" >
      {% for tip in tip_list %}
      <div class="card mb-4 rounded-2">
        {% if tip.image %}
        <img src= "{{ tip.image.url }}"  alt="{{tip.name}}" class="img-fluid">
        {% endif %}
        <div class="card-body">
          <small class="text-muted">Posted By: {% if tip.user.is_authenticated %} {{tip.user.get_username}} {% else %} Visitor {% endif %}</small>
          <br>
          <small class="text-muted">{{tip.date }}</small>
          <br><br>
          <h5 class="card-title">{{ tip.subject }}</h5>
          <p class="card-text">{{ tip.description }}</p>
          <p class="card-text">
          </p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}